import type { TrackerModalsProps } from '../modalTypes'

export type SettingsModalProps = Pick<
  TrackerModalsProps,
  | 'entries'
  | 'diapers'
  | 'medicines'
  | 'tummyTimes'
  | 'pumpEvents'
  | 'pumpSession'
  | 'tummySession'
  | 'growthMeasurements'
  | 'healthRecords'
  | 'customTrackers'
  | 'setCustomTrackers'
  | 'session'
  | 'babyDob'
  | 'tummyGoalMinutes'
  | 'pumpGoalOunces'
  | 'pumpGoalSessions'
  | 'feedingNotificationsEnabled'
  | 'browserRemindersEnabled'
  | 'notificationPermission'
  | 'notificationPreferences'
  | 'gotifyAvailable'
  | 'gotifyRemindersEnabled'
  | 'medicineReminderSettings'
  | 'babies'
  | 'selectedBabyId'
  | 'authUser'
  | 'profileName'
  | 'setProfileName'
  | 'theme'
  | 'onLogout'
  | 'fileInputRef'
  | 'setSettingsOpen'
  | 'setEntries'
  | 'setDiapers'
  | 'setMedicines'
  | 'setTummyTimes'
  | 'setPumpEvents'
  | 'setPumpSession'
  | 'setTummySession'
  | 'setGrowthMeasurements'
  | 'setHealthRecords'
  | 'setBabyDob'
  | 'setTummyGoalMinutes'
  | 'setPumpGoalOunces'
  | 'setPumpGoalSessions'
  | 'setSession'
  | 'setUndoState'
  | 'setFeedingNotificationsEnabled'
  | 'setBrowserRemindersEnabled'
  | 'liveSyncEnabled'
  | 'setLiveSyncEnabled'
  | 'setNotificationPreferences'
  | 'setTheme'
  | 'enableBrowserReminders'
  | 'setGotifyReminders'
  | 'setMedicineReminderSettings'
  | 'onCreateBaby'
  | 'onRenameBaby'
  | 'onUpdateBabyProfile'
  | 'onArchiveBaby'
  | 'showToast'
> & {
  /** Which tab to open on, when something outside Settings sends you to one. */
  initialTab?: 'profile' | 'reminders' | 'assistant' | 'baby' | 'household' | 'appearance' | 'account' | 'data'
}
